<?php

function csas_dvl_ob($vars = array(), $filename = '', $rel_path = 'sites/default/files/tmp/') {
  ob_start();
  print_r($vars);
  $plain = ob_get_contents();
  ob_end_clean();

  if ($handle = fopen($_SERVER['DOCUMENT_ROOT'] . base_path() . $rel_path . "temp_" . $filename . "_" . microtime() . ".txt", 'w+')) {
    fwrite($handle, $plain . "\n");
    fclose($handle);
  }
}

/**
 * Implementation of hook_menu().
 */
function csas_dvl_menu() {
  $items['admin/config/content/csas_dvl'] = array(
    'title' => 'Csas dvl',
    'description' => 'Csas dvl',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('csas_dvl_admin_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'csas_dvl.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_preprocess_page().
 */
function csas_dvl_preprocess_page(&$variables) {

  //renewal css & js
  if (variable_get('csas_dvl_clear_js_css', FALSE)) {
    _drupal_flush_css_js();
  }
}